Project - Post Data to APIs
Objective: Learn how to send data from Salesforce to an external API.

Challenge:

Integrate Salesforce with the Twilio SMS API.
When a new Opportunity is created, send an SMS notification.
Use a trigger on the Opportunity object to invoke the callout.
Bonus:

Include dynamic data (e.g., Opportunity Name, Amount, or Stage) in the message or SMS.
Create a custom setting to control which Opportunities trigger the integration (e.g., only when Stage = "Closed Won").

Solution:
1.Create Twilio Account, then  get your Account SID(USf6c782bcbdb60a8dca0b61deacb736e2) and Auth Token()
2.Create an Account within Twilio + phone number (here is mine: +18445484915)

